apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
#    role: test-pod
spec:
  containers:
    - name: test-pod
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
#  restartPolicy: Always
  