# 서비스의 역할은 파드로 들어오는 요청을 관리하는 것!
apiVersion: v1
kind: Service
metadata:
  name: test-service  # 서비스 이름
spec:
  type: NodePort      # 서비스의 유형
  ports:              # 포트 설정
    - port: 8099      # 서비스 포트
      targetPort: 8080 # 파드 포트
      protocol: TCP
      nodePort: 30080 # 워커 노드의 포트 (30000 ~ 32767) localhost:30080 <- 이렇게 접근 가능
  selector:           # 셀렉터 설정
    app: test-deploy
